FROM node:20.1-slim as base

FROM base as deps

WORKDIR /home/node/app
COPY package.json package-lock.json ./

RUN npm install --package-lock-only --include=dev


FROM base AS builder

WORKDIR /home/node/app
COPY . .
COPY --from=deps /home/node/app/node_modules ./node_modules
RUN npm run build --no-lint 


FROM base as dev

WORKDIR /home/node/app

EXPOSE 3000

CMD [ "npm", "run", "dev" ]


FROM base as prod

ENV NODE_ENV=production
ENV PAYLOAD_CONFIG_PATH=dist/payload.config.js

WORKDIR /home/node/app

COPY package.json package-lock.json ./
COPY --from=deps /home/node/app/node_modules ./node_modules
COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/build ./build

EXPOSE 3000

CMD ["npm", "run", "serve"]
